import type { RateLimitPolicyDefinition, RateLimitPolicyKey } from "./types.js";

export const RATE_LIMIT_POLICIES: Record<RateLimitPolicyKey, RateLimitPolicyDefinition> = {
  "auth.signin": {
    key: "auth.signin",
    description: "Protect email/password sign-in against brute force attempts.",
    enabled: true,
    windowSeconds: 15 * 60,
    anonymousMaxRequests: 8,
    tags: ["auth", "security", "bruteforce"],
    routePatternHints: ["POST /api/v1/auth/signin"],
    priority: 100,
    bucketStrategy: "ip_email_route",
  },
  "auth.signup": {
    key: "auth.signup",
    description: "Protect signup from abuse and email delivery bursts.",
    enabled: true,
    windowSeconds: 30 * 60,
    anonymousMaxRequests: 5,
    tags: ["auth", "email", "cost"],
    routePatternHints: ["POST /api/v1/auth/signup"],
    priority: 100,
    bucketStrategy: "ip_route",
  },
  "auth.resendVerification": {
    key: "auth.resendVerification",
    description: "Strictly guard verification resend to protect email quotas.",
    enabled: true,
    windowSeconds: 30 * 60,
    anonymousMaxRequests: 3,
    tags: ["auth", "email", "abuse"],
    routePatternHints: ["POST /api/v1/auth/resend-verification"],
    priority: 100,
    bucketStrategy: "ip_email_route",
  },
  "auth.refresh": {
    key: "auth.refresh",
    description: "Protect refresh-token rotation endpoint from abuse.",
    enabled: true,
    windowSeconds: 15 * 60,
    anonymousMaxRequests: 30,
    tags: ["auth", "security"],
    routePatternHints: ["POST /api/v1/auth/refresh"],
    priority: 90,
    bucketStrategy: "ip_route",
  },
  "auth.passkeyOptions": {
    key: "auth.passkeyOptions",
    description: "Protect passkey options pre-auth route.",
    enabled: true,
    windowSeconds: 10 * 60,
    anonymousMaxRequests: 8,
    tags: ["auth", "passkey", "security"],
    routePatternHints: ["POST /api/v1/auth/passkey/options"],
    priority: 90,
    bucketStrategy: "ip_email_route",
  },
  "auth.passkeyVerify": {
    key: "auth.passkeyVerify",
    description: "Protect passkey verify pre-auth route.",
    enabled: true,
    windowSeconds: 10 * 60,
    anonymousMaxRequests: 8,
    tags: ["auth", "passkey", "security"],
    routePatternHints: ["POST /api/v1/auth/passkey/verify"],
    priority: 90,
    bucketStrategy: "ip_route",
  },
  "auth.passwordChange": {
    key: "auth.passwordChange",
    description: "Protect password change operations.",
    enabled: true,
    windowSeconds: 60 * 60,
    authenticatedMaxRequests: 6,
    tags: ["auth", "security", "account"],
    routePatternHints: ["POST /api/v1/auth/change-password"],
    priority: 100,
    bucketStrategy: "user_route",
  },
  "auth.deleteAccount": {
    key: "auth.deleteAccount",
    description: "Protect account deletion endpoint.",
    enabled: true,
    windowSeconds: 60 * 60,
    authenticatedMaxRequests: 3,
    tags: ["auth", "security", "account"],
    routePatternHints: ["POST /api/v1/auth/delete"],
    priority: 100,
    bucketStrategy: "user_route",
  },
  "security.sensitive": {
    key: "security.sensitive",
    description: "Protect sensitive security configuration endpoints.",
    enabled: true,
    windowSeconds: 10 * 60,
    authenticatedMaxRequests: 12,
    tags: ["security", "mfa", "passkey"],
    routePatternHints: [
      "POST /api/v1/security/mfa",
      "POST /api/v1/security/passkeys",
      "POST /api/v1/security/passkeys/register/options",
      "POST /api/v1/security/passkeys/register/verify",
    ],
    priority: 100,
    bucketStrategy: "user_route",
  },
  "chat.createThread": {
    key: "chat.createThread",
    description: "Control chat thread creation volume.",
    enabled: true,
    windowSeconds: 10 * 60,
    authenticatedMaxRequests: 20,
    tags: ["chat", "cost"],
    routePatternHints: ["POST /api/v1/chat/threads"],
    priority: 80,
    bucketStrategy: "user_route",
  },
  "chat.sendMessage": {
    key: "chat.sendMessage",
    description: "Protect paid LLM chat completion usage.",
    enabled: true,
    windowSeconds: 60,
    authenticatedMaxRequests: 20,
    tags: ["chat", "llm", "cost"],
    routePatternHints: ["POST /api/v1/chat", "POST /api/v1/chat/threads/:id/messages"],
    priority: 100,
    bucketStrategy: "user_route",
  },
  "chat.threadMutation": {
    key: "chat.threadMutation",
    description: "Protect thread mutation endpoints from abuse.",
    enabled: true,
    windowSeconds: 5 * 60,
    authenticatedMaxRequests: 30,
    tags: ["chat"],
    routePatternHints: [
      "PATCH /api/v1/chat/threads/:id",
      "DELETE /api/v1/chat/threads/:id",
      "POST /api/v1/chat/threads/:id/branch",
      "POST /api/v1/chat/threads/:id/events",
    ],
    priority: 70,
    bucketStrategy: "user_route",
  },
  "email.trigger": {
    key: "email.trigger",
    description: "Reserved policy for endpoints that trigger outbound email delivery.",
    enabled: true,
    windowSeconds: 10 * 60,
    anonymousMaxRequests: 6,
    authenticatedMaxRequests: 20,
    tags: ["email", "cost", "abuse"],
    routePatternHints: ["/api/v1/* (email-triggering routes)"],
    priority: 85,
    bucketStrategy: "ip_route",
  },
  "llm.expensiveAction": {
    key: "llm.expensiveAction",
    description: "Protect non-chat expensive LLM actions.",
    enabled: true,
    windowSeconds: 10 * 60,
    authenticatedMaxRequests: 12,
    tags: ["llm", "cost"],
    routePatternHints: [
      "POST /api/v1/chat/threads/:id/context/summarize",
      "POST /api/v1/reflections",
      "POST /api/v1/reflections/:id/commentary/regenerate",
      "POST /api/v1/reflections/:id/retry",
      "POST /api/v1/reflections/:id/send-to-companion",
    ],
    priority: 100,
    bucketStrategy: "user_route",
  },
  "preview.chat": {
    key: "preview.chat",
    description: "Protect anonymous preview chat cost exposure.",
    enabled: true,
    windowSeconds: 60,
    anonymousMaxRequests: 6,
    tags: ["preview", "llm", "cost", "anonymous"],
    routePatternHints: ["POST /api/v1/preview/chat"],
    priority: 100,
    bucketStrategy: "ip_user_agent_route",
  },
  "preview.events": {
    key: "preview.events",
    description: "Protect preview analytics event ingestion from spam.",
    enabled: true,
    windowSeconds: 60,
    anonymousMaxRequests: 45,
    tags: ["preview", "analytics", "anonymous"],
    routePatternHints: ["POST /api/v1/preview/events"],
    priority: 60,
    bucketStrategy: "ip_user_agent_route",
  },
  "admin.contentMutation": {
    key: "admin.contentMutation",
    description: "Guard admin content mutation bursts.",
    enabled: true,
    windowSeconds: 60,
    authenticatedMaxRequests: 90,
    tags: ["admin", "content"],
    routePatternHints: ["/api/v1/admin/content/*"],
    priority: 70,
    bucketStrategy: "user_route",
  },
  "admin.systemUnlock": {
    key: "admin.systemUnlock",
    description: "Guard system lock unlock endpoint.",
    enabled: true,
    windowSeconds: 10 * 60,
    authenticatedMaxRequests: 4,
    tags: ["admin", "ops", "security"],
    routePatternHints: ["POST /api/v1/admin/system/jobs/unlock"],
    priority: 90,
    bucketStrategy: "user_route",
  },
  "admin.inviteUser": {
    key: "admin.inviteUser",
    description: "Reserved policy for future invite-user endpoints.",
    enabled: true,
    windowSeconds: 60 * 60,
    authenticatedMaxRequests: 20,
    tags: ["admin", "invite", "email"],
    routePatternHints: [
      "POST /api/v1/admin/invitations",
      "POST /api/v1/admin/invitations/:id/revoke",
    ],
    priority: 80,
    bucketStrategy: "user_route",
  },
};
